source 'https://rubygems.org'

gem 'icalendar'                       # for dealing with iCalendar files
gem 'memoist'                         # memoize methods

group :test do
  gem 'rspec'
  gem 'rspec-its'                     # its(:foo) syntax
  gem 'guard-rspec', require: false
end
